# JVM arguments for the Gradle daemon.
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
# AndroidX.
android.useAndroidX=true
# Kotlin code style.
kotlin.code.style=official
# Only build the resources needed by the app (faster builds).
android.nonTransitiveRClass=true
# Parallel builds and caching.
org.gradle.parallel=true
org.gradle.caching=true
