# RATIG ProGuard/R8 rules.
# kotlinx-serialization: keep serializers generated by the plugin.
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.AnnotationsKt

-keepclassmembers class kotlinx.serialization.json.** {
    *** Companion;
}
-keepclasseswithmembers class kotlinx.serialization.json.** {
    kotlinx.serialization.KSerializer serializer(...);
}
-keep,includedescriptorclasses class com.ratig.app.**$$serializer { *; }
-keepclassmembers class com.ratig.app.** {
    *** Companion;
}
-keepclasseswithmembers class com.ratig.app.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# Supabase / Ktor
-dontwarn org.slf4j.**
-dontwarn io.ktor.**
