package com.ratig.app.data.remote.dto

import com.ratig.app.core.json.InstantAsStringSerializer
import com.ratig.app.domain.model.ApprovalStatus
import com.ratig.app.domain.model.FatigueRule
import com.ratig.app.domain.model.ProtocolConfiguration
import com.ratig.app.domain.model.ProtocolStatus
import com.ratig.app.domain.model.RuleConfig
import com.ratig.app.domain.model.TestProtocol
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import java.time.Instant

/**
 * DTOs for `test_protocols` and `fatigue_rules`. jsonb columns
 * (`configuration`, `config`) decode as [JsonElement] and are mapped to the
 * typed domain configuration via [ProtocolConfiguration.fromJson] /
 * [RuleConfig.fromJson].
 */

@Serializable
data class TestProtocolDto(
    val id: String,
    val name: String,
    @SerialName("protocol_version") val protocolVersion: String,
    @SerialName("trial_count") val trialCount: Int,
    @SerialName("stimulus_delay_min_ms") val stimulusDelayMinMs: Long,
    @SerialName("stimulus_delay_max_ms") val stimulusDelayMaxMs: Long,
    @SerialName("response_timeout_ms") val responseTimeoutMs: Long,
    val configuration: JsonElement = JsonNull,
    val status: ProtocolStatus = ProtocolStatus.DRAFT,
    @SerialName("created_by") val createdBy: String? = null,
    @SerialName("approved_by") val approvedBy: String? = null,
    @SerialName("created_at") @Serializable(with = InstantAsStringSerializer::class)
    val createdAt: Instant? = null,
) {
    fun toDomain(): TestProtocol = TestProtocol(
        id = id,
        name = name,
        protocolVersion = protocolVersion,
        trialCount = trialCount,
        stimulusDelayMinMs = stimulusDelayMinMs,
        stimulusDelayMaxMs = stimulusDelayMaxMs,
        responseTimeoutMs = responseTimeoutMs,
        configuration = ProtocolConfiguration.fromJson(configuration.toRawJsonString()),
        status = status,
        createdBy = createdBy,
        approvedBy = approvedBy,
        createdAt = createdAt,
    )
}

/** Insert payload for a new draft protocol (id is generated by the database). */
@Serializable
data class ProtocolInsertDto(
    val name: String,
    @SerialName("protocol_version") val protocolVersion: String,
    @SerialName("trial_count") val trialCount: Int,
    @SerialName("stimulus_delay_min_ms") val stimulusDelayMinMs: Long,
    @SerialName("stimulus_delay_max_ms") val stimulusDelayMaxMs: Long,
    @SerialName("response_timeout_ms") val responseTimeoutMs: Long,
    val configuration: JsonElement,
    val status: String = "draft",
    @SerialName("created_by") val createdBy: String,
)

@Serializable
data class FatigueRuleDto(
    val id: String,
    @SerialName("protocol_id") val protocolId: String,
    @SerialName("rule_version") val ruleVersion: String,
    val config: JsonElement = JsonNull,
    @SerialName("effective_from") @Serializable(with = InstantAsStringSerializer::class)
    val effectiveFrom: Instant,
    @SerialName("effective_until") @Serializable(with = InstantAsStringSerializer::class)
    val effectiveUntil: Instant? = null,
    @SerialName("approval_status") val approvalStatus: ApprovalStatus = ApprovalStatus.DRAFT,
    @SerialName("created_by") val createdBy: String? = null,
    @SerialName("approved_by") val approvedBy: String? = null,
    @SerialName("created_at") @Serializable(with = InstantAsStringSerializer::class)
    val createdAt: Instant? = null,
) {
    fun toDomain(): FatigueRule = FatigueRule(
        id = id,
        protocolId = protocolId,
        ruleVersion = ruleVersion,
        config = RuleConfig.fromJson(config.toRawJsonString()),
        effectiveFrom = effectiveFrom,
        effectiveUntil = effectiveUntil,
        approvalStatus = approvalStatus,
        createdBy = createdBy,
        approvedBy = approvedBy,
        createdAt = createdAt,
    )
}

/** Insert payload for a new draft rule (id is generated by the database). */
@Serializable
data class FatigueRuleInsertDto(
    @SerialName("protocol_id") val protocolId: String,
    @SerialName("rule_version") val ruleVersion: String,
    val config: JsonElement,
    @SerialName("effective_from") @Serializable(with = InstantAsStringSerializer::class)
    val effectiveFrom: Instant,
    @SerialName("effective_until") @Serializable(with = InstantAsStringSerializer::class)
    val effectiveUntil: Instant? = null,
    @SerialName("approval_status") val approvalStatus: String = "draft",
    @SerialName("created_by") val createdBy: String,
)

private fun JsonElement.toRawJsonString(): String? =
    if (this is JsonNull) null else toString()
